import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {canScore,readHistory,writeHistory,appendFirst,referenceFeedback,traceReady,escapeHTML} from '../trainer/case-state.js';
import {topics} from '../trainer/case-content.js';
import {regions} from '../trainer/regions.js';
const manifest=JSON.parse(fs.readFileSync(new URL('../trainer/assets/cases/manifest.json',import.meta.url)));
test('automatic subject segmentation cannot be scored, even if a flag is accidentally changed',()=>{
 for(const c of manifest.cases)for(const label of c.segmentation.labels){assert.equal(canScore({status:'expert-verified',scoring:'validated-region'},label),false);assert.equal(canScore({status:'expert-verified',scoring:'validated-region'},{...label,scoreable:true}),false);}
});
test('first response is immutable and does not manufacture a clinical score',()=>{const h=readHistory({getItem:()=>null});const a={id:'same',score:100,note:'first'};assert.equal(appendFirst(h,a),true);assert.equal(appendFirst(h,{...a,note:'changed'}),false);assert.equal(h.attempts[0].note,'first');assert.equal(h.attempts[0].score,null);});
test('corrupt or blocked storage degrades without losing live session',()=>{assert.deepEqual(readHistory({getItem:()=>'{'}).attempts,[]);assert.deepEqual(readHistory({getItem(){throw Error('blocked')}}).attempts,[]);assert.equal(writeHistory({},{setItem(){throw Error('quota')}}),false);});
test('held-out subject cannot appear in learning cohort',()=>{const learning=manifest.cases.filter(c=>c.cohort==='learning'),transfer=manifest.cases.filter(c=>c.cohort==='transfer');assert.equal(learning.length,3);assert.equal(transfer.length,1);assert.ok(!learning.some(c=>transfer.some(t=>t.id===c.id)));});
test('native T1 retains signed 16-bit intensity and acquisition versus file geometry',()=>{for(const c of manifest.cases){assert.equal(c.kind,'individual');assert.equal(c.sequences.T1w.dtype,'int16');assert.equal(c.sequences.T1w.sha256,c.sequences.T1w.native.sha256);assert.equal(c.sequences.T2w.dtype,'float32');assert.ok(c.sequences.T1w.voxel_size[0]<.7);assert.deepEqual(c.sequences.T1w.acquisition_voxel_size,[.7,.7,.7]);assert.equal(c.segmentation.foreground_correlation,1);}});
test('3D topic references select the intended structure',()=>{for(const t of topics.filter(t=>t.group!=null)){const r=regions[t.group];const map={hippocampus:'Hippocampus',amygdala:'Amygdala',insula:'Insula',thalamus:'Thalamus',caudate:'Caudate',putamen:'Putamen',pallidum:'Globus pallidus',cingulate:'cingulate',accumbens:'accumbens',parahippocampal:'parahippocampal',orbitofrontal:'orbitofrontal',precuneus:'precuneus','inferior-parietal':'IPL'};assert.ok(r.en.toLowerCase().includes(map[t.id].toLowerCase()),t.id);}});
test('absence feedback is explicitly reference extent, not a fabricated image answer',()=>{const t=topics[0],c=manifest.cases[0];const result=referenceFeedback({side:'left',plane:'coronal',point:[0,999,0]},c.segmentation.labels,t);assert.ok(result.comparison.includes('범위 밖'));assert.ok(result.comparison.includes('검수된 정답은 아니며'));const missing=referenceFeedback({side:'left',plane:'axial',point:[0,0,0]},c.segmentation.labels,topics.find(t=>t.id==='internal-capsule'));assert.equal(missing.target,null);});
test('trace requires ordered distinct slices of the same plane',()=>{const p=(y,plane='coronal')=>({point:[0,y,0],plane});assert.equal(traceReady({appearance:p(0),body:p(0),disappearance:p(0)}),false);assert.equal(traceReady({appearance:p(0),body:p(1),disappearance:p(2)}),true);assert.equal(traceReady({appearance:p(2),body:p(1),disappearance:p(0)}),true);assert.equal(traceReady({appearance:p(2),body:p(1,'axial'),disappearance:p(0)}),false);assert.equal(traceReady({appearance:p(0),body:p(2),disappearance:p(1)}),false);});
test('observation prose remains inert when rendered in history and feedback',()=>{assert.equal(escapeHTML('<img src=x onerror="alert(1)">'),'&lt;img src=x onerror=&quot;alert(1)&quot;&gt;');});
test('corrupt draft trace does not crash or forge a submitted response',async()=>{const {restoreTask}=await import('../trainer/case-state.js');assert.equal(restoreTask({id:'x',note:'valid',hints:[],marks:{appearance:'bad'},visited:{}},{attempts:[]}),null);const restored=restoreTask({id:'x',note:'valid',hints:[],marks:{},visited:{},submitted:{note:'forged'}},{attempts:[]});assert.equal(restored.submitted,null);});
