import {chromium,expect} from '@playwright/test';
import fs from 'node:fs';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
const state=()=>page.evaluate(()=>window.mriCaseQA.snapshot());
const ready=()=>page.waitForFunction(()=>window.mriCaseQA&&!window.mriCaseQA.snapshot().loading&&!window.mriCaseQA.snapshot().loadError,undefined,{timeout:120000});
const aim=async selector=>{await page.locator(selector).scrollIntoViewIfNeeded();const box=await page.locator(selector).boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);};
const wheel=async(delta,command=false)=>{if(command)await page.keyboard.down('Meta');await page.mouse.wheel(0,delta);await page.waitForTimeout(100);if(command)await page.keyboard.up('Meta');};
try{
 await page.goto('http://127.0.0.1:8091/');await page.locator('#cases-mode').click();await ready();await page.locator('[data-case-mode=explore]').click();await page.locator('[data-topic=thalamus]').click();await page.locator('[data-workspace=mri]').click();
 await aim('#case-mri');let before=await state();await wheel(-120,true);let after=await state();expect(after.viewer.zoom).toBeGreaterThan(before.viewer.zoom);expect(after.viewer.point).toEqual(before.viewer.point);expect(Number(await page.locator('#case-zoom').inputValue())).toBeCloseTo(after.viewer.zoom,2);await expect(page.locator('#case-zoom-value')).toHaveText(`${Number(after.viewer.zoom.toFixed(2))}×`);checks.push('Command + real wheel zooms and synchronizes controls without moving the slice/crosshair');
 before=after;await wheel(120);after=await state();expect(after.viewer.point).not.toEqual(before.viewer.point);expect(after.viewer.zoom).toBe(before.viewer.zoom);checks.push('Unmodified real wheel still changes cut level without changing zoom');
 await page.locator('#case-anchor').click();await aim('#case-mri');await page.mouse.click(...await page.evaluate(()=>{const s=window.mriCaseQA.snapshot(),p=window.mriCaseQA.projectPoint(s.viewer.point,s.viewer.plane),r=document.querySelector('#case-mri').getBoundingClientRect();return [r.x+p[0],r.y+p[1]];}));await page.waitForTimeout(100);before=await state();expect(before.nearby.items.length).toBeGreaterThan(0);await page.locator('.nearby-dot').first().hover();await wheel(-120,true);after=await state();expect(after.viewer.zoom).toBeGreaterThan(before.viewer.zoom);expect(after.viewer.point).toEqual(before.viewer.point);expect(after.nearby.items).toEqual(before.nearby.items);checks.push('Command wheel over a yellow marker also zooms, preserving nearby structures');
 await aim('#case-mri');before=await state();for(let i=0;i<8;i++)await wheel(-1000,true);expect((await state()).viewer.zoom).toBe(4);for(let i=0;i<8;i++)await wheel(1000,true);expect((await state()).viewer.zoom).toBe(1);expect((await state()).viewer.point).toEqual(before.viewer.point);checks.push('Zoom clamps at 1x and 4x; reaching either limit does not scroll slices');
 await wheel(-120,true);before=await state();await page.locator('[data-sequence=T2w]').click();await ready();after=await state();expect(after.viewer.zoom).toBe(before.viewer.zoom);expect(Number(await page.locator('#case-zoom').inputValue())).toBeCloseTo(after.viewer.zoom,2);checks.push('T2 preserves the actual zoom and matching slider display');
 await page.locator('[data-case-mode=compare]').click();await page.waitForFunction(()=>window.mriCaseQA.snapshot().comparison&&!window.mriCaseQA.snapshot().comparison.busy,undefined,{timeout:120000});await aim('#case-compare-mri');before=await state();await wheel(-120,true);after=await state();expect(after.comparison.zoom).toBeGreaterThan(before.comparison.zoom);expect(after.comparison.point).toEqual(before.comparison.point);expect(after.viewer.zoom).toBe(before.viewer.zoom);checks.push('Comparison image supports independent Command wheel zoom');
 await page.locator('#explore-mode').click();await page.waitForFunction(()=>document.querySelector('#mri-loading').hidden,undefined,{timeout:120000});await page.locator('[data-plane=axial]').click();await page.locator('[data-workspace=mri]').click();await aim('#mri');const coords=await page.locator('#coordinates').textContent();const zoom=Number(await page.locator('#zoom').inputValue());await wheel(-120,true);expect(Number(await page.locator('#zoom').inputValue())).toBeGreaterThan(zoom);await expect(page.locator('#coordinates')).toHaveText(coords);checks.push('Reference Atlas supports the same shortcut without moving its coordinate');
 expect(errors).toEqual([]);checks.push('No uncaught browser errors');console.log(checks.join('\n'));fs.writeFileSync('trainer/qa/wheel-zoom-report.json',JSON.stringify({date:new Date().toISOString(),checks,errors},null,2));
}finally{await browser.close();}
