import {expandedTopics} from './case-content-expanded.js';
// Authored observation prompts. Reference segmentations never become clinical answer keys.
const anatomy='https://radiologyassistant.nl/neuroradiology/brain/anatomy';
const basal='https://nba.uth.tmc.edu/neuroanatomy/L5/Lab05p20_index.html';
const capsule='https://nba.uth.tmc.edu/neuroanatomy/L10/Lab10p01_index.html';
const nm='https://pmc.ncbi.nlm.nih.gov/articles/PMC11526017/';
export const topics=[
 {id:'hippocampus',ko:'해마',en:'Hippocampus',group:17,plane:'coronal',landmarks:['측뇌실 측두각의 CSF','해마곁이랑과 내측 측두엽','앞쪽 편도체와의 이행'],prompt:'측두각 아래의 해마를 앞에서 뒤로 추적하세요. 머리·몸통·꼬리의 형태 변화와 양측 차이를 말로 설명하세요.',relation:'측두각의 아래쪽에서 시작해 뒤쪽 연속 단면으로 확인합니다. 앞쪽에서는 편도체와 해마의 이행이 불명확할 수 있으므로 시상면도 함께 봅니다.',boundary:'해마 전체의 자동 분할입니다. 세부 아영역이나 편도체와의 한 복셀 경계는 정답이 아닙니다.',pitfall:'측두각 CSF나 해마곁이랑을 해마 실질로 잡지 않았는지 확인하세요.',clinical:'내측 측두엽을 평가하기 위한 위치·형태 관찰 연습입니다. 표준 관상면은 해마 장축에 직교한 관상 사위면과 다르며, 이 앱에서 MTA 점수나 진단을 산출하지 않습니다.',source:anatomy},
 {id:'amygdala',ko:'편도체',en:'Amygdala',group:16,plane:'coronal',landmarks:['해마 머리','내측 측두엽 앞부분','측두각'],prompt:'해마 머리를 먼저 찾은 뒤 그 앞·위쪽에서 편도체 위치를 추론하세요. 실제 신호로 보이는 경계와 추론한 경계를 구분하세요.',relation:'해마 머리의 앞·위쪽 내측 측두엽에 있습니다. 한 절편의 색보다 앞뒤 연속성과 다른 방향에서의 위치가 근거입니다.',boundary:'해마와의 이행부와 피질 인접 경계는 T1/T2에서 항상 명확하지 않습니다. 자동 분할과 다르다는 이유로 오답 처리하지 않습니다.',pitfall:'해마 머리를 편도체로 지목하지 않았는지 앞뒤 단면에서 다시 확인하세요.',clinical:'변연계 위치를 확인하는 훈련입니다. 구조의 형태만으로 정서 기능이나 정신과 진단을 추정하지 않습니다.',source:anatomy},
 {id:'caudate',ko:'미상핵',en:'Caudate',group:1,plane:'axial',landmarks:['측뇌실 전각','내포 앞다리','조가비핵'],prompt:'측뇌실 전각에 붙은 머리를 찾고 위쪽 단면에서 몸통으로 이어지는 모습을 추적하세요.',relation:'미상핵 머리는 측뇌실 전각의 가쪽에 인접합니다. 렌즈핵 쪽과 사이의 내포 앞다리를 찾아 구별합니다.',boundary:'머리·몸통보다 가느다란 꼬리의 경계가 어렵습니다. 자동 분할의 끝이 실제 조직의 끝과 일치한다고 가정하지 않습니다.',pitfall:'전각의 검은 CSF와 미상핵 회색질을 구별하고, 내포 너머 조가비핵인지 확인하세요.',clinical:'전두엽–선조체 회로를 해부학적 랜드마크에 연결합니다. 회로의 기능적 경계를 T1 위에 그리지는 않습니다.',source:basal},
 {id:'putamen',ko:'조가비핵',en:'Putamen',group:0,plane:'axial',landmarks:['담창구·창백핵','내포','뇌섬엽 방향'],prompt:'렌즈핵의 가쪽 부분을 찾고 담창구·내포와의 관계를 세 방향에서 확인하세요.',relation:'담창구보다 가쪽에 있습니다. 미상핵과 시상에서 내포를 건너 렌즈핵을 찾은 뒤 안팎을 구별합니다.',boundary:'조가비핵과 담창구의 대비는 시퀀스·위치에 따라 다릅니다. 보이지 않는 경계를 임의로 확정하지 않습니다.',pitfall:'조가비핵 바깥 백질이나 더 가쪽 뇌섬엽 피질을 함께 포함하지 않았는지 확인하세요.',clinical:'기저핵 주변을 빠짐없이 보는 관찰 경로를 익힙니다.',source:basal},
 {id:'pallidum',ko:'담창구 · 창백핵',en:'Globus pallidus (whole)',group:4,plane:'axial',landmarks:['조가비핵의 안쪽','내포','렌즈핵'],prompt:'조가비핵보다 안쪽에 있는 담창구 전체를 찾고 T1/T2에서 신호 대비가 어떻게 달라지는지 서술하세요.',relation:'렌즈핵 안쪽 부분이며 조가비핵과 내포 사이에 놓입니다. 이 개인 분할은 담창구 전체입니다.',boundary:'개인 MRI에서 안쪽분절·바깥분절을 구분해 채점하지 않습니다. 3D 참고 모델의 안쪽분절·바깥분절 구획과 개인 전체 분할을 구별하세요.',pitfall:'내포 백질을 담창구로 잡지 않았는지 확인하세요. T2 저신호만으로 병적 철 침착을 판단하지 않습니다.',clinical:'구조의 위치와 시퀀스별 신호를 구분해서 기록하는 연습입니다.',source:basal},
 {id:'thalamus',ko:'시상',en:'Thalamus',group:28,plane:'axial',landmarks:['제3뇌실','내포 뒷다리','미상핵 뒤쪽'],prompt:'제3뇌실 양옆의 시상을 찾고 가쪽 내포와의 경계를 연속 단면에서 확인하세요.',relation:'제3뇌실 가쪽에 있으며, 더 가쪽의 렌즈핵과는 내포 뒷다리로 구별합니다.',boundary:'시상 전체 자동 분할입니다. 개별 시상핵은 이 T1/T2에서 직접 식별하는 정답 영역이 아닙니다.',pitfall:'제3뇌실이나 시상 아래쪽 영역을 포함하지 않았는지 세 방향에서 확인하세요.',clinical:'심부 회색질을 양측 비교하고 주변 백질과 구별하는 훈련입니다.',source:basal},
 {id:'insula',ko:'뇌섬엽',en:'Insula',group:21,plane:'coronal',landmarks:['외측고랑','덮개(operculum)','조가비핵보다 가쪽'],prompt:'외측고랑 깊은 곳에서 뇌섬엽 피질을 찾고 덮개에 가려지는 관계를 확인하세요.',relation:'외측고랑 안쪽 깊이에 있는 피질입니다. 조가비핵에서 가쪽으로 이동하면 백질층을 지나 뇌섬엽 피질에 도달합니다.',boundary:'고랑 주변 피질 경계의 자동 추출 오차와 부분용적 효과가 있습니다.',pitfall:'조가비핵이나 외측 덮개 피질을 뇌섬엽으로 지목하지 않았는지 확인하세요.',clinical:'피질 구조와 심부 핵을 섞지 않고 같은 단면에서 위치 관계를 설명합니다.',source:anatomy},
 {id:'cingulate',ko:'대상회',en:'Cingulate gyrus',group:19,plane:'sagittal',landmarks:['뇌량','뇌량고랑','대상고랑'],prompt:'정중선 옆 시상면에서 뇌량 위를 따라 대상회를 추적하세요. 앞·뒤 부분의 연속성을 다른 방향으로 확인하세요.',relation:'뇌량 위쪽에서 뇌량고랑과 대상고랑 사이를 따라 확인합니다. 뒤쪽으로는 뇌량 팽대부 주변의 연결을 살펴봅니다.',boundary:'FreeSurfer의 앞·뒤·isthmus 구획을 합친 참고 영역입니다. dACC 같은 기능적 경계는 아닙니다.',pitfall:'뇌량 백질 또는 그보다 위쪽 피질을 함께 포함하지 않았는지 고랑을 기준으로 확인하세요.',clinical:'대상회 위치와 DMN 등 기능적 네트워크의 정의를 구분합니다.',source:anatomy},
 {id:'ventricle',ko:'측뇌실',en:'Lateral ventricle',group:null,plane:'axial',landmarks:['전각과 미상핵','몸통과 뇌량','측두각과 해마'],prompt:'전각·몸통·뒤쪽 부분으로 이어지는 CSF 공간을 추적하고 T1/T2 신호를 비교하세요.',relation:'전각은 미상핵 머리에 인접하고, 측두각은 해마를 찾는 단서입니다. 정중 제3뇌실과는 구별합니다.',boundary:'제공 라벨은 FreeSurfer lateral-ventricle 구획이며 inferior-lateral-ventricle 별도 라벨은 포함하지 않습니다. 측두각 전체 범위의 정답으로 사용하지 않습니다.',pitfall:'고랑 CSF와 측뇌실, 제3뇌실을 혼동하지 않았는지 연속성을 확인하세요.',clinical:'CSF 공간과 실질의 관계를 관찰합니다. 크기만으로 수두증이나 위축을 진단하지 않습니다.',source:anatomy},
 {id:'callosum',midline:true,ko:'뇌량',en:'Corpus callosum',group:null,plane:'sagittal',landmarks:['무릎(genu)','몸통(body)','팽대부(splenium)'],prompt:'정중 시상면에서 뇌량을 앞에서 뒤로 따라가고, 대상회와 측뇌실의 관계를 설명하세요.',relation:'정중 시상면의 활 모양 백질 구조를 먼저 찾고 다른 방향에서 양측 반구로 이어지는 모습을 봅니다.',boundary:'FreeSurfer의 중앙 뇌량 5구획을 합친 라벨입니다. 가쪽 모든 뇌량 섬유의 범위를 나타내지 않습니다.',pitfall:'위쪽 대상회 회색질이나 아래쪽 뇌궁을 뇌량에 포함하지 않았는지 확인하세요.',clinical:'정중선 랜드마크를 먼저 잡아 방향과 연속성을 확인하는 연습입니다.',source:anatomy},
 {id:'internal-capsule',ko:'내포',en:'Internal capsule',group:null,plane:'axial',landmarks:['미상핵·시상(안쪽)','렌즈핵(가쪽)','앞다리–무릎–뒷다리'],prompt:'미상핵과 렌즈핵 사이 앞다리, 시상과 렌즈핵 사이 뒷다리를 연결해 설명하세요.',relation:'내포 앞다리는 미상핵 머리와 렌즈핵 사이, 뒷다리는 시상과 렌즈핵 사이에 놓입니다. 무릎은 그 두 부분이 만나는 굽은 구간입니다.',boundary:'이 사례에는 검수된 내포 전용 라벨이 없습니다. 주변 구조를 통해 관찰하고 색 경계나 위치 점수는 제공하지 않습니다.',pitfall:'조가비핵 바깥의 외포를 내포와 혼동하지 않도록 안쪽 회색질 랜드마크부터 짚으세요.',clinical:'백질 통로를 주위 회색질과의 관계로 읽는 훈련입니다.',source:capsule},
 ...expandedTopics
];
const categories={hippocampus:'내측 측두엽 · 변연계',amygdala:'내측 측두엽 · 변연계',cingulate:'내측 측두엽 · 변연계',insula:'전두 · 두정 피질',ventricle:'뇌실 · 백질 랜드마크',callosum:'뇌실 · 백질 랜드마크','internal-capsule':'뇌실 · 백질 랜드마크'};
for(const t of topics)t.category??=categories[t.id]??'심부 회색질';
export const visibilityLesson={source:nm,text:'일반 T1/T2에서 LC·VTA·봉선핵·NBM·PPTN·외측중격핵의 경계를 직접 구분했다고 평가하지 않습니다. SN·LC의 직접 관찰에는 neuromelanin-sensitive MRI 등 표적 대비와 사례별 검증이 필요합니다. dlPFC·vmPFC·DMN·CSTC는 구조적 랜드마크에 연결하는 기능적 참고입니다.'};
export const modes={explore:'자유 탐색',guided:'구조 찾기 연습',trace:'연속 추적',compare:'비교',transfer:'전이 연습'};
export const statusNames={present:'이 단면에서 위치를 찾음',absent:'이 단면에는 없다고 판단',indeterminate:'현재 대비로 식별하기 어려움'};
